language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - npm i -g yarn
install:
  - yarn
before_script:
  - git config --global user.name "jaeyoung.choi"
  - git config --global user.email "lactrious@gmail.com"
script:
  - "yarn deploy"
