name: "Update blog"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone this repository"
        uses: actions/checkout@v1

      #  https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: "Build and deploy"
        run: |
          git config user.email "${USER_EMAIL}"
          git config user.name "${USER_NAME}"
          yarn deploy
        env:
          GH_PAGES_BRANCH: master
          GH_PAGES_REPO: ${{ secrets.GH_PAGES_REPO }}
          USER_EMAIL: "lactrious@gmail.com"
          USER_NAME: "jaeyoung.choi"
